version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest                # Use the latest MongoDB image
    container_name: mongo_db           # Set the container name
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # Initialize the MongoDB with a root username
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword  # Initialize the MongoDB with a root password
    volumes:
      - mongodb_data:/data/db         # Mount a volume to persist MongoDB data
    ports:
      - "27017:27017"                 # Expose the MongoDB port on localhost

  # Node.js Application service
  user-service:
    build:
      context: .                       # Build the Dockerfile in the current directory
    container_name: user_service      # Set the container name for the app
    environment:
      - MONGO_URI=mongodb://root:rootpassword@mongo:27017/user-service # MongoDB URI
      - PORT=5000                       # Set the app's port
    depends_on:
      - mongo                          # Ensure the MongoDB service starts first
    ports:
      - "5000:5000"                    # Expose the Node.js app port on localhost
    volumes:
      - .:/usr/src/app                 # Mount the current directory for live reloading

# Define named volumes
volumes:
  mongodb_data:
    driver: local
